const heroSlides = [
  {
    image: "https://ik.imagekit.io/ADORN/ADORN/Products/Hero/hero-3.jpg",
    alt: "Woman in sunglasses leaning out of a vintage green car with a handbag",
    phoneTransform: "w-800",
    desktopTransform: "w-1920,h-1020,fo-face,z-0.25",
    phonePosition: "50% 0%",
    desktopPosition: "50% 50%",
    textSide: "left",
    heading: "The new season edit",
    headline: "Everyday luxury, delivered across Ghana.",
    sentence: "Bags, beauty, jewellery and more, chosen for how you really live.",
    button: { text: "Shop new arrivals", to: "/" },
    secondButton: { text: "Browse bags", to: "/category/bags" },
  },
  {
    image: "https://ik.imagekit.io/ADORN/ADORN/Products/Hero/hero-1.jpg",
    alt: "Woman in a bathrobe applying face cream in front of a mirror",
    phoneTransform: "w-800",
    desktopTransform: "w-1920",
    phonePosition: "32% 50%",
    desktopPosition: "50% 55%",
    textSide: "right",
    heading: "The skincare edit",
    headline: "Glow starts with good skin.",
    sentence: "Creams, serums and shea butter for skin that feels as good as it looks.",
    button: { text: "Shop skincare", to: "/category/skincare" },
    secondButton: { text: "Shop makeup", to: "/category/makeup" },
  },
  {
    image: "https://ik.imagekit.io/ADORN/ADORN/Products/Hero/hero-2.jpg",
    alt: "Perfume bottle on black sequins with a flower and a gold chain",
    phoneTransform: "w-800",
    desktopTransform: "w-1920",
    phonePosition: "52% 50%",
    desktopPosition: "50% 50%",
    textSide: "left",
    heading: "Fragrance",
    headline: "A scent to remember.",
    sentence: "Fragrances to carry you from morning to night.",
    button: { text: "Shop perfumes", to: "/category/perfumes" },
    secondButton: { text: "Browse jewellery", to: "/category/jewellery" },
  },
];

export default heroSlides;
